# Use postgres/example user/password credentials
version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '80:80'
    restart: always
    networks:
      - stocker
  api:
    build:
      context: .
      dockerfile: dockerfiles/api.dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - '3011:3011'
    volumes:
      - v-stocker-api:/app/node_modules
      - ./:/app
    networks:
      - stocker
    depends_on:
      - nginx
  db:
    image: postgres:14-alpine
    container_name: stocker-postgres-db
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=${POSTGRES_SCHEMA}&connect_timeout=30&pool_timeout=30
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - stocker
networks:
  stocker:
    external: true
    name: stocker
volumes:
  v-stocker-api:
  postgres:
    name: v-stocker-pg-data
